Updated hash for Github Actions

diff --git a/.github/workflows/branch-name-validator.yml b/.github/workflows/branch-name-validator.yml
--- a/.github/workflows/branch-name-validator.yml
+++ b/.github/workflows/branch-name-validator.yml
@@ -6,8 +6,22 @@ jobs:
   check-jira-prefix:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v5
-      - uses: deepakputhraya/action-branch-name@master
-        with:
-          regex: '^(no-ticket/|renovate[-/]|hotfix/|IPB-[0-9]+/)' # start branch with either 'no-ticket/' or 'IPB-NUMBER/', allowing for bots and hotfixes
-          ignore: main
+      - name: Check out branch
+      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
+      - name: Validate branch name
+        run: |
+          # Extract branch name from GITHUB_HEAD_REF (for PRs)
+          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+          
+          echo "Branch name: $BRANCH_NAME"
+          
+          # Define allowed pattern: feature/*, bugfix/*, hotfix/*, release/*
+          PATTERN="^(no-ticket/|renovate[-/]|hotfix/|IPB-[0-9]+/|COS-[0-9]+/)"
+          
+          if [[ ! "$BRANCH_NAME" =~ $PATTERN ]]; then
+            echo "❌ Branch name '$BRANCH_NAME' is invalid."
+            echo "Allowed format: no-ticket/NAME or IPB-[JIRANUMBER]/name"
+            exit 1
+          fi
+          
+          echo "✅ Branch name is valid."
